### ISSUE TITLE
IE9 Support incomplete.

### ISSUE THREAD

**Issue by nick-somebody** [andersevenrud/select-typeahead#1]
Firstly, classList calls fail for IE9. I was able to workaround that with this shim https://github.com/eligrey/classList.js

Secondly, CustomEvent has no support in IE, https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent I was able to workaround that with the polyfill in that article.

Not sure how you want to handle this but currently your lib doesn't support IE9+ as claimed in your README.

With the above 2 issues handled, I have it working in IE9.

**Comment by andersevenrud** [comment]
Thank you for reporting. This is a regression for a change I made down the line.

I'll probably add a proper build script here to make a bundle that contains what you've mentioned.

**Comment by andersevenrud** [comment]
This should no longer be an issue as I provide bundles in the `dist/` directory.

Please re-open if you still have issues after this.
