### ISSUE TITLE
onChange Callback

### ISSUE THREAD

**Issue by schellenbergk** [andersevenrud/select-typeahead#3]
Is there a way to tap into change event?

I've tried:

```
typeahead.$target.addEventListener("change",(e) =>{
        console.log('changed: ',e);
});
```

but no success.

**Comment by andersevenrud** [comment]
Try using the `select` event instead and then look up the entry with `e.detail`.

**Comment by andersevenrud** [comment]
Note that the `select` event is non-standard. If I remember correctly it was implemented to be used in replacement of `onchange` :)

**Comment by schellenbergk** [comment]
thanks!

**Comment by andersevenrud** [comment]
No problem :ok_hand:
